### ISSUE TITLE
identifier "_udiv128" is undefined

### ISSUE THREAD

**Issue by werdegars** [kanhavishva/KeyHunt-Cuda-2#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0020	identifier "_udiv128" is undefined	KeyHunt-Cuda-2	KeyHunt-Cuda-2\KeyHunt-Cuda-2\Int.cpp	1091	

how to solve this?

**Comment by kanhavishva** [comment]
Install windows sdk properly.

**Comment by werdegars** [comment]
ok i have managed to compile but in debug mode only
when i changed to release mode, so many errors

how about prefix address instead of full address?
do you plan to implement that?

**Comment by kanhavishva** [comment]
post the errors here, i can help you to solve them.

prefix searching is already implemented as [Vanity Search](https://github.com/JeanLucPons/VanitySearch) and [vanitygen](https://github.com/samr7/vanitygen).

**Comment by kanhavishva** [comment]
please do all discussion and issues to main repo: https://github.com/kanhavishva/KeyHunt-Cuda.git
