### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by oneitguy** [kanhavishva/KeyHunt-Cuda-2#2]
Could you add a "--continue FILE" 

--continue FILE
    Save/load progress from FILE

Example 

https://github.com/brichard19/BitCrack

**Comment by kanhavishva** [comment]
i'll do that later

**Comment by kanhavishva** [comment]
please do all discussion and issues to main repo: https://github.com/kanhavishva/KeyHunt-Cuda.git
