### ISSUE TITLE
random mode request

### ISSUE THREAD

**Issue by studyroom1** [kanhavishva/KeyHunt-Cuda-2#3]
hi bro , thanks for really amazing work .can you please implement random mode thank you

**Comment by kanhavishva** [comment]
working on that

**Comment by nft30001** [comment]
i saw when i loaded 2 addresses it is using gpu memory 5gb out of 10 in rtx 3080 & when u load million of addresses it is also using same memory in GPU but some additional from RAM. need a bit explanation please.
why GPU memory utilization is not going above 5.8GB?
if gpu memory is still available why utilize from RAM? kind of slow right?

 lets say my  GPU have 68 cores so is it possible to utilize each core as a  separate worker with separate bloom filter? plus random mode , i am seriously hopping i will get my BTC back :(

**Comment by studyroom1** [comment]
> working on that

thank you !!

**Comment by exterity** [comment]
@kanhavishva Amazing Key Hunt compared to Vanity Search. Thank you so much!!! May you add -stride option from starting key?

**Comment by nft30001** [comment]
@kanhavishva  any update bro ?

**Comment by nft30001** [comment]
@kanhavishva do you have email address please? share with me need to discuss

**Comment by kanhavishva** [comment]
please do all discussion and issues to main repo: https://github.com/kanhavishva/KeyHunt-Cuda.git
