### ISSUE TITLE
Always random

### ISSUE THREAD

**Issue by okay1903** [kanhavishva/KeyHunt-Cuda-2#4]
hello, is it possible to generate new random key every time? not just at startup.

Generate random -> check key -> generate random --> check key. like this.

**Comment by kanhavishva** [comment]
i have tried that way too, it is very slow

**Comment by okay1903** [comment]
how slow per second?

**Comment by okay1903** [comment]
can you make always random please. I've tried for make but i failed. beacause i not good for cuda.

**Comment by kanhavishva** [comment]
please do all discussion and issues to main repo: https://github.com/kanhavishva/KeyHunt-Cuda.git
